// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7TqfDrPpgAomA-JK3N4A7-YRQKKwQ1M8',
    appId: '1:301545055646:web:678fecbcebc23cb3d4228f',
    messagingSenderId: '301545055646',
    projectId: 'dnd-arcanum-c17f6',
    authDomain: 'dnd-arcanum-c17f6.firebaseapp.com',
    storageBucket: 'dnd-arcanum-c17f6.firebasestorage.app',
    measurementId: 'G-BBW8PWEKK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqXHjXtnTdPcPNb-DJ6Ea9j1U1uiwbd8',
    appId: '1:301545055646:android:52567e9effc81993d4228f',
    messagingSenderId: '301545055646',
    projectId: 'dnd-arcanum-c17f6',
    storageBucket: 'dnd-arcanum-c17f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwwgV1Y5zGmyzZBnknBv0zpa3uaIV1DY4',
    appId: '1:301545055646:ios:f2dfff3d2d1e276fd4228f',
    messagingSenderId: '301545055646',
    projectId: 'dnd-arcanum-c17f6',
    storageBucket: 'dnd-arcanum-c17f6.firebasestorage.app',
    iosBundleId: 'com.aracanum.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwwgV1Y5zGmyzZBnknBv0zpa3uaIV1DY4',
    appId: '1:301545055646:ios:f2dfff3d2d1e276fd4228f',
    messagingSenderId: '301545055646',
    projectId: 'dnd-arcanum-c17f6',
    storageBucket: 'dnd-arcanum-c17f6.firebasestorage.app',
    iosBundleId: 'com.aracanum.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7TqfDrPpgAomA-JK3N4A7-YRQKKwQ1M8',
    appId: '1:301545055646:web:9dd6cb30a039b4f1d4228f',
    messagingSenderId: '301545055646',
    projectId: 'dnd-arcanum-c17f6',
    authDomain: 'dnd-arcanum-c17f6.firebaseapp.com',
    storageBucket: 'dnd-arcanum-c17f6.firebasestorage.app',
    measurementId: 'G-RSQLMN5Q0S',
  );
}
